import sys
x='vijay'
def my_display(x):
    print('Name:')
    print(x)
sys.displaybook=my_display
x

# DO THE TYPING AND EXECUTION IN SHELL.
#RESULTS WON'T BE SEEN IN IDE'S BECAUSE OF LINE BY LINE EXECUTION IS NOT POSSIBLE.
# INSTEAD IN SHELL LINE BY LINE EXECTION HAPPENS AND THE COMMANDS ARE STORED SYSTEMS MEMORY.

# SYSTEM PATH MODIFICATION ISN'T POSSIBLE IN PYTHON BUT IS POSSIBLE IN PYTHON SHELL.
